### PR TITLE
CHE-1296: Use docker auth config saved in user preferences to start machine from private image

### PR DESCRIPTION
**Pull request by mmorhun**
Signed-off-by: Mykola Morhun <mmorhun@codenvy.com>

### CODE REVIEW

**Comment by mmorhun** [comment]
@garagatyi take a look please

**Comment by garagatyi** [comment]
LGTM

**Comment by garagatyi** [comment]
@skabashnyuk Please take a look

**Comment by skabashnyuk** [comment]
ok

**Pull request merged**
