### PR TITLE
CODENVY-1739: Do not make additional http request on each license check

### PR DESCRIPTION
**Pull request by mmorhun**
### What does this PR do?
Caches Fair Source License acceptance to prevent multiple requests with the same result.

### What issues does this PR fix or reference?
#1739 

#### Changelog
Optimizes Fair Source license checks to improve performance.

#### Release Notes
We've optimized the performance of all HTTP requests by caching the necessary license checks.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Will it cache requests if license is **NOT** accepted?

**Comment by skabashnyuk** [comment]
Ok. And what is the problem? What if it will be 1 minute? And the opposite task. If license was ok but expired during tomcat life time should it be revalidated after X minutes?

**Comment by tolusha** [comment]
> And what is the problem? What if it will be 1 minute?
I user could login after license had been accepted it would be awkward.
 
> If license was ok but expired during tomcat life time should it be revalidated after X minutes?
Agree.
@mmorhun  Take it into account.

**Comment by mmorhun** [comment]
ci-build

**Pull request merged**
