### PR TITLE
add preflight port checks for swarm and socat

### PR DESCRIPTION
**Pull request by riuvshin**
add preflight port checks for swarm and socat

---
This change is [Reviewable](https://reviewable.io/reviews/codenvy/codenvy/1471)

### CODE REVIEW

**Comment by TylerJewell** [comment]
I will combine this PR with the other one related to separating dev mode and repo mounting concepts.

**Comment by riuvshin** [comment]
those changes not related to separation. and why we need separate? I thought we will only add debug for non dev mode. separation means big unnecessary changes (from my POV) I don't understand value of that separation, because if you've mounted repo that means you want to develop which require debug.

**Comment by TylerJewell** [comment]
I will incorporate these changes into the separation PR as I had to rewrite some parts of the cmd_start() functionality to make it work consistently.  This issue is related to swarm port stuff, so let's not litigate other issues related to swarm port here.

**Comment by TylerJewell** [comment]
I think you can close this issue now - I have incorporated it into my bigger fixes on this PR: https://github.com/codenvy/codenvy/pull/1458#issuecomment-270386276

**Pull request closed without merging**
