### PR TITLE
CODENVY-499: Ways to mount folder inside host machine to auxiliary machine

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do?
Add ability to mount extra volumes in Codenvy

### CODE REVIEW

**Comment by tolusha** [comment]
@sleshchenko 
@garagatyi 
pls review

**Comment by benoitf** [comment]
what's the difference with `machine.server.extra.volume` property ?

**Comment by benoitf** [comment]
it's backporting https://github.com/eclipse/che/blob/b2309ef34510be5dd00fa6d37dc1e5bf69b5dff1/plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/LocalDockerModule.java#L68-L71 to codenvy ?

**Comment by tolusha** [comment]
`machine.server.extra.volume` is a property for user to set extra volumes to mount.
`machine.docker.dev_machine.machine_volume` is used inside che to collect all mounts

**Comment by garagatyi** [comment]
Please change title and commit message: CODENVY-499, not CHE-499

**Comment by garagatyi** [comment]
Looks like binding for dev machine is not needed. Use binding for all machines instead.

**Comment by garagatyi** [comment]
Also, please, move provider in Che out of local package and fix javadocs to not declare binding for dev machines only.

**Comment by tolusha** [comment]
@garagatyi 
updated

**Comment by garagatyi** [comment]
LGTM

**Comment by skabashnyuk** [comment]
щл

**Pull request merged**
