### PR TITLE
CODENVY-610: add possibility to config no_proxy property

### PR DESCRIPTION
**Pull request by dmytro-ndp**
@riuvshin: please, review this request.

Signed-off-by: Dmytro Nochevnov <dnochevnov@codenvy.com>

### CODE REVIEW

**Comment by riuvshin** [comment]
OK

**Comment by TylerJewell** [comment]
1. you probably should move the no_proxy option to be next to the http_proxy options.
2. Do we need matching no_proxy options for docker & codenvy workspaces attributes?  They are in the same section of the document.

**Comment by riuvshin** [comment]
1) +0 that file is not for humans, humans should use CLI or manifests
2) we don't know the rules what we should put there, in case of TIAA to workaround their bug we should put same dns but maybe some customer will want set up no proxy for some other host which maybe reasonable.
so I would say it looks as expected.
default value is empty because we don't know what customer will want to set here.

**Comment by TylerJewell** [comment]
+1  

Do we have command line parameter for bootstrap script?

**Comment by dmytro-ndp** [comment]
No, we don't.

**Comment by dmytro-ndp** [comment]
I could add it.

**Pull request merged**
