### PR TITLE
CHE-1770: New layout for forms in UD

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?
Provides new layout for form in UD.

### What issues does this PR fix or reference?
[https://github.com/eclipse/che/issues/1770](https://github.com/eclipse/che/issues/1770)
[Make factory creation and edit screens identical](https://github.com/codenvy/codenvy/issues/554)

### CODE REVIEW

**Comment by akurinnoy** [comment]
Factory details:
factory-details

**Comment by akurinnoy** [comment]
Factory configuration:
factory-configuration

**Comment by akurinnoy** [comment]
Create factory:
create-factory

**Comment by akurinnoy** [comment]
Profile:
profile

**Comment by TylerJewell** [comment]
@ashumilova @akurinnoy - first, very impressive.

Two thoughts:
1: Can we shrink the size of the font in the configuration editor where the JSON is displayed to match the size of the font for the labels?  If you notice in the JSON box, the font for the JSON is slightly larger than the other fonts on the screen.  Let's just be consistent as it will look better.

2: On the "Create Factory" page a number of things:
2a: You say "Configure Factory" in the title on top, but you called this the "Create Factory" page.
2b: After the Factory exists and the user goes to "configuration" the only thing that appears is the JSON box.  Shouldn't all of these fields appear in both locations?
2c: The "Configure Actions" section looks super weird.  Can it be formatted like the "Configure Commands" section?  

A+ job here.

**Comment by slemeur** [comment]
The overall work is nice, there are few details that are needing refinements and polish.

In Factory Creation form:
- [ ] Remove “Github” tab
- [ ] Rename the title of the screen by “New Factory From"
- [ ] Rename tabs: “Workspaces” by “Workspace” / “Config file” by “Factory Config”

Also see https://github.com/eclipse/che/pull/2061

**Comment by slemeur** [comment]
New feedbacks on the Factory Creation flow:
screen shot 2016-08-17 at 15 55 41

- [ ] Page title must be "New Factory From"
- [ ] Rename "Git Repository" tab by "Git"
- [ ] Rename "Factory Config" by "Config"
- [ ] In the description of the "Git URL", displayed in gray should be "Repository URL"
- [ ] Make "Workspace" first in the list of choices

In the factory details form:
screen shot 2016-08-17 at 18 13 17

- [ ] Change the font in the config json editor to be smaller
- [ ] In the table of predefined commands and actions. first column must be left-top justified
- [ ] Add field description for Configration: "JSON definition of the factory."
- [ ] for field "Delete Factory", add "." at the end of the description "This is irreversible."
- [ ] for configuring an action, second textfield, add the "." at the end of the warning message "Param is required."

In edit registries popup:
screen shot 2016-08-17 at 18 15 14

- [ ] For field password, remove the "User" from warning message to be "Password is required."

**Pull request merged**
