### PR TITLE
CODENVY-1009: fix license legality check

### PR DESCRIPTION
**Pull request by ashumilova**
### What does this PR do?

Fix license legality check.

### What issues does this PR fix or reference?

https://github.com/codenvy/codenvy/issues/1009

Signed-off-by: Ann Shumilova <ashumilova@codenvy.com>

### CODE REVIEW

**Comment by ashumilova** [comment]
@riuvshin License legality on nightly5 should be checked, cause now it's false.

**Comment by riuvshin** [comment]
@ashumilova nightly5 is not onprem it is saas we can't check this on saas

**Comment by ashumilova** [comment]
Then saas should not have license service deployed, if it's not used, or it should return correct value, like on beta now. Not sure, but the result of this issue https://github.com/codenvy/codenvy/issues/599 may cause it.

**Comment by dmytro-ndp** [comment]
@riuvshin, @ashumilova: https://codenvy.io has Codenvy license and so it returns legalilty=true.
https://nightly5.codenvy-stg.com doesn't has Codenvy license and, as a result it's legalilty=false.
And it doesn't matter are they kind of _SaaS_ or _on-prem_ now.

**Pull request merged**
