### PR TITLE
CHE-1081: remove workspace id usage in wsagent services

### PR DESCRIPTION
**Pull request by ashumilova**
Signed-off-by: Ann Shumilova <ashumilova@codenvy.com>

### CODE REVIEW

**Comment by ashumilova** [comment]
References on [this PR](https://github.com/eclipse/che/pull/1268/commits/f7027e58698dfbc5dd5a5d7c6ffc13f0227e1416)

**Comment by vparfonov** [comment]
@skabashnyuk @garagatyi

**Comment by garagatyi** [comment]
LGTM

**Comment by skabashnyuk** [comment]
ok

**Comment by benoitf** [comment]
it seems this pull request about dashboard has been hijacked by changes on another area

**Comment by ashumilova** [comment]
renamed the title of PR for those changes to be merged at once

**Comment by benoitf** [comment]
I see commits without JIRA issues in this PR

**Comment by vparfonov** [comment]
https://jira.codenvycorp.com/browse/CHE-1081 this is related issue

**Comment by benoitf** [comment]
I know but it is not written in the commit message
image

**Comment by garagatyi** [comment]
IMO it is not so essential to block that PR. By the way we don't have an agreement about that.

**Pull request merged**
