### PR TITLE
CODENVY-454: Remove error log when machine was stopped while its backup task was in executor queue

### PR DESCRIPTION
**Pull request by mmorhun**
### What does this PR do?
Handle machine not found exception in backup scheduler
### What issues does this PR fix or reference?
#454
### Previous Behavior
Logged error about attempt to backup stooped machine 
### New Behavior
Just skip backup in such case, because it is normal behaviour
### Tests written?
Yes

### CODE REVIEW

**Comment by mmorhun** [comment]
@garagatyi take a look please

**Comment by garagatyi** [comment]
LGTM

**Comment by mmorhun** [comment]
@skabashnyuk ?

**Comment by skabashnyuk** [comment]
ok

**Pull request merged**
