### PR TITLE
Add indexes to Workers, Recipe and Stack Permissions

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Add indexes to Workers, Recipe and Stack Permissions

@evoevodin @akorneta @skabashnyuk @mshaposhnik 
Please review my changes

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok.

**Comment by mshaposhnik** [comment]
Ok

**Comment by akorneta** [comment]
ok

**Comment by evoevodin** [comment]
Good job! LGTM

**Pull request merged**
