### PR TITLE
Start to make some common files for codenvy/cli and eclipse/che-cli 

### PR DESCRIPTION
**Pull request by benoitf**
- allow to use ansi text with printf
- add ansi text formatting constants
- replace "/codenvy" by $CHE_CONTAINER_ROOT
- replace "codenvy" by $CHE_MINI_PRODUCT_NAME
- replace "Codenvy" by $CHE_PRODUCT_NAME
- initialize usage in its own function (for allowing to override constant)
- add sh script to build the cli image 

- use of eclipse/che-base as base image for common scripts for both eclipse/che-cli and codenvy/cli

### CODE REVIEW

**Comment by benoitf** [comment]
pr updated

**Comment by TylerJewell** [comment]
These are all approved changes

**Comment by benoitf** [comment]
@TylerJewell

**Comment by riuvshin** [comment]
why this merged with only one approve? 
why  CLI using `FROM eclipse/che-base:nightly` ? how you guys going to manage it with other versions?

**Comment by benoitf** [comment]
When che is tagged, che images are tagged
Codenvy is using che so codenvy cli image will use che-base tagged image as eclipse/che-cli

**Comment by riuvshin** [comment]
I mean how you are going to keep nightly CLI always using actual che-base ? 
those changes affect processes like release and CI 
CI: to merge this PR we have to set up trigger on CI to rebuild CLI if che-base was changed ( I think due to this CLI does not work on my side at all.)
Release: that affected release process because we need to set those tags here, and there is no any info about that, this is super important because If I will do tag and will not set tags before we won't be able to build images from that tag. So I need strategy here how I should release this what are the steps before I start and etc.

**Comment by riuvshin** [comment]
I've added dependency on CI, now each build of `che-base:nightly` will trigger `cli:nightly`
I also added docker pull `eclipse/che-base:nightly` in CLI job to make sure it is actual if they will run on separate CI slaves.

But for releases I don't see whole picture I think we have to write somewhere docker images dependencies and keep it always up to date

**Pull request merged**
