### PR TITLE
CODENVY-641: Add factory permission filter

### PR DESCRIPTION
**Pull request by akorneta**
Now factory service getFromJson method permissions will be covered by FactoryPermissionsFilter
@skabashnyuk, @sleshchenko please review

### CODE REVIEW

**Comment by benoitf** [comment]
Where is filter test ?

**Comment by skabashnyuk** [comment]
@akorneta  up to you. Please add test if it's possible and we have technique for that. Please consult with @sleshchenko .

**Comment by sleshchenko** [comment]
LGTM but +1 to add tests

**Comment by benoitf** [comment]
I saw @mshaposhnik adding filter test as well

**Comment by riuvshin** [comment]
guys can we add test with another PR because we don't have time for release. and we cant start QA cycle without this.

**Comment by riuvshin** [comment]
Whoa! Thanks A LOT @sleshchenko  for adding test! what  hero!

**Comment by riuvshin** [comment]
@skabashnyuk @benoitf @vparfonov we need review here and merge asap

**Pull request merged**
