### PR TITLE
Update code based on CHE #3798 updates

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
After Che PR https://github.com/eclipse/che/pull/3798 code has been broken

### What issues does this PR fix or reference?
 https://github.com/eclipse/che/pull/3798 

### New Behavior
should compile again

maybe it needs update for swarm for this part
https://github.com/eclipse/che/blob/1ec641a7e823eb7ff1092d26654d720fc7c949d7/plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/LocalDockerModule.java#L69-L71

### Tests written?
tests updated

### Docs requirements?
no

### CODE REVIEW

**Comment by garagatyi** [comment]
@benoitf @riuvshin Please don't merge. It is not finished yet.

**Comment by garagatyi** [comment]
@riuvshin I checked codenvy works with this fix

**Comment by benoitf** [comment]
@riuvshin @garagatyi I let you merge pr whenever you want.

**Comment by benoitf** [comment]
@garagatyi yes thx for the updates on the fix. I was not able to test changes at runtime

**Pull request merged**
