### PR TITLE
[WIP] Move AdminUserDao functionality to UserDao

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What issues does this PR fix or reference?
https://github.com/codenvy/codenvy/issues/586

### New Behavior
Move getAll method from AdminUserDao to UserDao. Remove AdminUserDao

### Tests written?
Yes

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok. @akorneta @evoevodin

**Comment by skabashnyuk** [comment]
ok

**Comment by skabashnyuk** [comment]
ok

**Comment by sleshchenko** [comment]
OK for me

**Comment by akorneta** [comment]
ok

**Pull request merged**
