### PR TITLE
che-1518: Fix creation zombie prosess when user closes terminal.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/1518

### Previous Behavior
After click close button user will see in the list of processes terminal (/bin/bash) zombie process 

### Tests written?
No

### Docs requirements?
Include the content for all the docs changes required. 
1.  API changes  : without changes
2.  User docs changes  : without changes

### CODE REVIEW

**Comment by garagatyi** [comment]
LGTM

**Comment by skabashnyuk** [comment]
@garagatyi @evoevodin  up to you to decide should we merge this pr or not

**Comment by garagatyi** [comment]
Since @riuvshin is going to do release on Monday, maybe Tuesday, I suggest to postpone merge. @evoevodin @riuvshin WDYT?

**Comment by TylerJewell** [comment]
We are going to make the release for early next week non-shippable. It will only be for internal testing - so we will make the following release (4.8) a shippable release. So slipping is ok - it's going to be in next customer shipment regardless.

**Comment by bmicklea** [comment]
@AndrienkoAleksandr is this something that is going to be merged this week?

**Comment by JamesDrummond** [comment]
@vkuznyetsov Please review.

**Pull request merged**
