### PR TITLE
(#479) add post-flight Codenvy on-prem installation check

### PR DESCRIPTION
**Pull request by dmytro-ndp**
@benoitf, @riuvshin, @tolusha - please, review this request.

Signed-off-by: Dmytro Nochevnov <dnochevnov@codenvy.com>

### CODE REVIEW

**Comment by riuvshin** [comment]
lgtm

**Comment by benoitf** [comment]
looks good, but it can only work after this https://github.com/eclipse/che/issues/1895 PR is merged as che-test post-flight test has been developed though this PR

**Comment by tolusha** [comment]
+1

**Comment by dmytro-ndp** [comment]
@benoitf: so, this changes will be merged into master after eclipse/che#1895 PR is merged.

**Pull request merged**
