### PR TITLE
CHE-718: Adapt hosted infrastructure to the model & API changes

### PR DESCRIPTION
**Pull request by evoevodin**
Move factory id into workspace intance attributes as workspace config doesn't have `attributes` field anymore.
@benoitf can you please review the changes related to the [dashboard](https://github.com/codenvy/codenvy/commit/41b8a7d76047af094fc0ef0ba39ccb744a0f5898)

@skabashnyuk, @garagatyi, @akorneta review please

### CODE REVIEW

**Comment by garagatyi** [comment]
So this PR make old data incompatible with new model.
- owner, attributes will be lost
- workspace indexes will be broken because of renaming field owner to namespace
Do you have solution for transition?

**Comment by evoevodin** [comment]
yes i developed mongo migration scripts

**Comment by akorneta** [comment]
ok

**Comment by garagatyi** [comment]
I believe you should add that script into this PR as it is an important part of these changes.

**Comment by evoevodin** [comment]
@garagatyi i attached script to the [issue](https://jira.codenvycorp.com/browse/CODENVY-343)

**Comment by evoevodin** [comment]
ci-build

**Comment by garagatyi** [comment]
LGTM

**Comment by skabashnyuk** [comment]
ok

**Pull request merged**
