### PR TITLE
CODENVY-1689: fix JSON parsing in email sender

### LINKED ISSUE #1689: Password recovery broken on codenvy.io
As per subject. Post requests returns 500

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Fixes JSON parsing in email sender service.

### What issues does this PR fix or reference?
Fixes #1689 

#### Changelog
Fix signup with email and password recovery features.

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by garagatyi** [comment]
@codenvy/pm please take a look

**Comment by bmicklea** [comment]
@garagatyi - I think you merged this so we could do the release quickly which is fine. Generally though you shouldn't merge until PM approves the PR. Also all PRs need a `kind/bug` or `kind/enhancement` label.

**Comment by garagatyi** [comment]
Sorry, I forgot to set labels. I merged PR because Sergii said that it is not mandatory to wait approval from PM team if this is a bug. Is it correct?

**Comment by bmicklea** [comment]
As long as it's labelled as a bug and the Changelog is there that's correct, you can merge without PM approval.

**Pull request merged**
