### PR TITLE
CODENVY-2350: Remove system license

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do?
Removes all system license checks. It means no more users limitation number.

### What issues does this PR fix or reference?
https://github.com/codenvy/codenvy/issues/2350

#### Changelog
Removes users limitation number.

#### Release Notes
Removes users limitation number.

#### Docs PR
https://github.com/codenvy/docs/pull/131

### CODE REVIEW

**Comment by riuvshin** [comment]
@tolusha are you sure that Docs PR is not required?  I think we have section in docs about that. @slemeur do you know where is this ? it seems we need help from docs owners to clean up the docs.

**Comment by bmicklea** [comment]
There are definitely docs changes needed to the scaling section at least (possibly more).

**Comment by tolusha** [comment]
https://github.com/codenvy/docs/pull/131

**Comment by tolusha** [comment]
@dmytro-ndp 
@vkuznyetsov is responsible for site changing. So it is out of the scope.

**Comment by bmicklea** [comment]
It may be out of scope for this issue but is part of the business requirement.

**Comment by dmytro-ndp** [comment]
@tolusha:
> saas/silexica they are another projects. Why did you mention them here?
It depends on **[onpremises-assembly-parent](https://github.com/codenvy/silexica/blob/master/pom.xml#L203)**, so it definitely ends up with broken login, IMHO

**Comment by dmytro-ndp** [comment]
@tolusha:
> @vkuznyetsov is responsible for site changing. So it is out of the scope.

**Comment by dmytro-ndp** [comment]
@tolusha: I propose to make all required changes for license removal, including changes dashboard and site, within one branch and then merge all of them at once.

**Comment by tolusha** [comment]
Ok .I don't mind.

**Comment by tolusha** [comment]
It starts now and works well

**Comment by tolusha** [comment]
@bmicklea 
So, should keep auditing the total number of users?

**Comment by tolusha** [comment]
Any way I restored printing the total number of users.

**Comment by bmicklea** [comment]
@tolusha, yes you are right - tracking total users is best even if we don't have a license it helps with capacity planning.

**Comment by tolusha** [comment]
https://github.com/codenvy/saas/pull/245
https://github.com/codenvy/silexica/pull/104
@dmytro-ndp

**Comment by dmytro-ndp** [comment]
Good job!

**Pull request merged**
