### PR TITLE
CHE-1342: improve navbar styles

### PR DESCRIPTION
**Pull request by olexii4**
selection_016
Signed-off-by: Oleksii Orel <oorel@codenvy.com>

### CODE REVIEW

**Comment by slemeur** [comment]
Since we updated the left-navbar, this issue must be reworked.

We will add into the menu that pops when clicking on "User Profile" at the bottom of the left-navbar, an item "Codenvy Classic".
This concern only codenvy-saas

**Comment by olexii4** [comment]
selection_006

**Comment by slemeur** [comment]
Profile & **A**ccount

Otherwise it is good

**Comment by olexii4** [comment]
done

**Pull request merged**
