### PR TITLE
CODENVY-601: fix WorkspaceFsBackupSchedulerTest

### PR DESCRIPTION
**Pull request by mmorhun**
### What does this PR do?
Fix WorkspaceFsBackupSchedulerTest.shouldBackupOtherWorkspacesIfBackupOfPreviousFails test

### What issues does this PR fix or reference?
#601 

### Previous Behavior
The test falls sometimes

### CODE REVIEW

**Comment by mmorhun** [comment]
@AndrienkoAleksandr @skabashnyuk ?

**Comment by AndrienkoAleksandr** [comment]
Ok for me

**Comment by akorneta** [comment]
ok

**Comment by skabashnyuk** [comment]
ok

**Comment by garagatyi** [comment]
LGTM. 
This test was removed, so you have conflict here. Please resolve conflict by restoring the test and applying your improvements.

**Pull request merged**
