### PR TITLE
CODENVY-617: add property of docker privilege mode

### PR DESCRIPTION
**Pull request by dmytro-ndp**
@riuvshin: please, review this request.

Signed-off-by: Dmytro Nochevnov <dnochevnov@codenvy.com>

### CODE REVIEW

**Comment by riuvshin** [comment]
why 4.2.0 version?

**Comment by dmytro-ndp** [comment]
Fixed.

**Comment by riuvshin** [comment]
LGTM

**Comment by TylerJewell** [comment]
@dmytro-ndp Please create jira issue assigned to me to document how users can set this in che / codenvy.  Please give me just some basic details of what the property is and where it is set in both places.

**Comment by dmytro-ndp** [comment]
@TylerJewell: here it is: https://jira.codenvycorp.com/browse/CODENVY-621

**Pull request merged**
