### PR TITLE
introduce CODEOWNERS

### PR DESCRIPTION
**Pull request by riuvshin**
### What does this PR do?
Introduce CODEOWNERS GH feature

There just a draft CODEOWNERS file to show how we can assign different engineers tobe codeowners in same project but for different places / modules.

there is few open questions:
1) should we require codeowner approve to allow PR merge? 
      - if yes PR will be blocker to merge unless codeowner approved (this could be tricky if codeowner is not available but we really need merge PR.)
      - if no any approve from reviewers will enable merge ( I'm +1 on this )

2) should we dismiss stale pull request approvals when new commits are pushed ? ( I'm -1 on this )

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/5593

#### Changelog
Introduce CODEOWNERS GH feature

### CODE REVIEW

**Comment by riuvshin** [comment]
@gazarenkov it is WIP for now, I just created this to discuss available options.

**Comment by slemeur** [comment]
Thanks @riuvshin .

On your questions, I agree with you:
1- require codeowner approve to allow PR merge if no any approve from reviewers. (+1)
2- dismiss stale pull request approvals when new commits are pushed (-1)

**Comment by riuvshin** [comment]
Once we will agree on settings and approach I will create PRs for all active projects.
Please note that to enable this feature in projects under eclipse org. I will request eclipse admins so it could take some time.

**Comment by TylerJewell** [comment]
I think that the list of maintainers proposed seems incomplete vs. the development process document that was developed.  Shouldn't there be multiple maintainers for each category and that we include the broader list?

**Comment by riuvshin** [comment]
working example https://github.com/codenvy/docs/pull/126 
I;ve set Stevan Brad and Eugene as owners in docs and they are automatically assigned to review.

@TylerJewell I used development process doc to assign maintainers, who you think is missing? (this is only related to Codenvy project for che and any other project we will have own list)

**Comment by riuvshin** [comment]
> Shouldn't there be multiple maintainers for each category and that we include the broader list?
I think we should not put many ppl there because all matched persons will be automatically assigned to review which may cause a lot of spam in notifications. 
Also please note that there is global owners section which means that in that project skabashnyuk will be assigned to ANY PR plus one or two extra reviewers depending on module.

**Comment by garagatyi** [comment]
I suppose it is a responsibility of maintainer to find correct reviewers for a PR.
Am I correct that maintainer doesn't have to be a reviewer in all the PRs he is assigned by CODEOWNERS feature?

**Comment by riuvshin** [comment]
@garagatyi with these changes at least one codeowner review will be needed to unblock merge.

**Comment by TylerJewell** [comment]
@riuvshin - I would think that we want the codereviewers to follow the complete maintainers list because the maintainer needs to make sure that the process is followed, and those maintainers can remove or add other necessary reviewers automatically.  The list that we had in the development process document is:

IDE: Vitalii Parfonov, Artem Zatsarynnyi
Language Servers, IDE Plugins: Dmitro Kuleshov,  Evgen Vidolob
Platform: Sergii Kabashnyuk, Alex Garagatyi
Kubernetes: Mario Loriedo, Gorkem Ercan
Dashboard: Anna Shumilova, Florent Benoit
QA Automation: Anatoliy Bazko
Utilities (CLI, devops, etc): Roman Iuvshin, Eugene Ivantsov
Docs: Stevan Lemeur, Eugene Ivantsov, Brad Micklea

**Comment by riuvshin** [comment]
@TylerJewell yes, I've proposed codeowners for codenvy project based on that list from dev process. Of course codeowners assigned to review automatically by CODEOWNERS feature can assign any other reviewer if needed.

I not quite understand are you ok with this concrete PR for codenvy project? Should I merge it and proceed adding CODEOWNERS for other projects or list of CODEOWNERS proposed here in codenvy project is NOT ok for you?

**Comment by riuvshin** [comment]
@gazarenkov sure, we can update that file whenever we want even person per plugin :)

**Comment by TylerJewell** [comment]
Should we tune the /plugins codeowners before merging?

**Comment by riuvshin** [comment]
@TylerJewell for codenvy project /pugins are already tuned, as there only a few of them skabashnyuk + garagatyi added for codenvy plugins as owners, I don;t know who else can be assigned to codenvy's plugins. For CHE project it will be more tricky because in CHE we have much more plugins and I will assign more ppl on them

**Pull request merged**
