### PR TITLE
Cleanup mail sending code

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Cleanup mail sending code - war is deleted, so mail sending is available now from API war only.

#### Changelog
Cleanup mail sending code - war is deleted, so mail sending is available now from API war only.

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by garagatyi** [comment]
@codenvy/pm It is not a butfix, but doesn't need to be in release notes

**Comment by garagatyi** [comment]
@codenvy/pm I suppose that :+1: from James was go for this PR. But can you guys add your review instead of reactions to PRs. Engineers are not notified by Github about reactions so don't know when you approve PR.

**Comment by JamesDrummond** [comment]
@garagatyi Please add me a reviewer if you would like me to review the PR. I thumbs up your comment about `It is not a bugfix, but doesn't need to be in release notes` which in generally is true. TL's will decide if release notes are needed for a PR for their team.

**Comment by garagatyi** [comment]
Should I always make you reviewer? What about Brad, Eugene, Stevan?

**Comment by bmicklea** [comment]
No need for PM review on this. You were correct.

**Comment by garagatyi** [comment]
Brad should I wait for PM approval/review next time?

**Comment by bmicklea** [comment]
For bugs and tasks that don't affect user experience you only need Changelog. No need for release notes and docs so no need for PM review.

**Comment by garagatyi** [comment]
Thank you for clarification!

**Pull request merged**
