### PR TITLE
Docker version check

### PR DESCRIPTION
**Pull request by mshaposhnik**
Add checking for docker client/server & API version

### CODE REVIEW

**Comment by TylerJewell** [comment]
@benoitf @mshaposhnik - requires matching improvement to be made in `cli-refactoring` branch of Eclipse Che.

**Comment by TylerJewell** [comment]
I am not sure we should be enforcing a check on client / daemon versions - given the scenarios with che-launcher and our ability to package up different CLI clients into other docker containers which can interact with many different versions of daemons.

**Comment by skabashnyuk** [comment]
@TylerJewell  it's not clear what to do with this pr. Should we abandon it?

**Comment by TylerJewell** [comment]
I am -1 on requiring that the docker client & server be identical.  I am +1 on requiring the docker server version being >1.11.

**Comment by mshaposhnik** [comment]
Removed version and API check

**Pull request merged**
