### PR TITLE
CODENVY-635: Create attachment files in separate temp directory

### PR DESCRIPTION
**Pull request by vinokurig**
This will resolve problem when two users send request for sending email at the same time, and sending second email fails.
@skabashnyuk please review

### CODE REVIEW

**Comment by benoitf** [comment]
should we have a test that reproduce race condition and then ensure it's gone and won't occur anymore ?

**Comment by vinokurig** [comment]
The problem is that `tempDir` is a local variable, I ca not mock it

**Comment by vinokurig** [comment]
It is very hard to reproduce this case in test conditions to test ti without mocks

**Comment by benoitf** [comment]
I see. I like tdd which means that before fixing it I'm able to have a testcase then I can change behavior and check test is fixed. So if class is not testable, for me it's a design error
And when bug is discovered we should have test case to ensure issue will not come back
But I see your point as well that current code is not testable it's just that it's not my way to think

**Comment by skabashnyuk** [comment]
ок

**Pull request merged**
