### PR TITLE
CODENVY-651 Use 'dev' instead 'isDev' for machine configs in Mongo

### PR DESCRIPTION
**Pull request by mkuznyetsov**
change MachineConfigImpl field 'isDev' to 'dev', as it is done in MachineConfigDto.
It should fix consitensy problems.

Also it needs to make migrations of existing workspaces.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok. @evoevodin ?

**Comment by evoevodin** [comment]
ok

**Comment by skabashnyuk** [comment]
ok. Do not merge until 4.6

**Comment by musienko-maxim** [comment]
After checking all tests we do not have any regressions as compared with nightly4 server.

**Pull request merged**
