### PR TITLE
Move DTO generation to the shared jar

### PR DESCRIPTION
**Pull request by vparfonov**
### What does this PR do?
Move DTO generation to the shared jar

Signed-off-by: Vitalii Parfonov <vparfonov@codenvy.com>

### CODE REVIEW

**Comment by vparfonov** [comment]
@skabashnyuk @riuvshin

**Comment by vparfonov** [comment]
@evoevodin

**Comment by riuvshin** [comment]
@benoitf wdyt?

**Comment by benoitf** [comment]
moving dto generation to shared will avoid to get issue of self-looking jar +1

**Pull request merged**
