### PR TITLE
CODENVY-434 Adapt Che URL and port config

### PR DESCRIPTION
**Pull request by stour**
Fix for platform-api-client-java integration tests.

@skabashnyuk @benoitf

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok

**Comment by benoitf** [comment]
I think that jmx server port can still collide, no ? the same for the shutdown port
If there is an existing tomcat server (like jenkins) I think it may kill jenkins instead of the integration tests 'internal tomcat'

**Comment by stour** [comment]
@benoitf I updated the PR in order to replace port 8005 and 8009 in server.xml and so avoid collision same as before.

**Comment by benoitf** [comment]
+1

**Comment by stour** [comment]
@skabashnyuk @benoitf could one of you please merge ?

**Comment by benoitf** [comment]
it seems I don't have the right to merge

**Pull request merged**
