### PR TITLE
CODENVY-370: dashboard for OnPrem must not include the button "Codenv…

### PR DESCRIPTION
**Pull request by akurinnoy**
…y Classic"

Signed-off-by: Oleksii Kurinnyi <okurinnyi@codenvy.com>

### CODE REVIEW

**Comment by benoitf** [comment]
I think this is not what I've discussed on JIRA entry BTW
but ok as quickfix

**Comment by benoitf** [comment]
based on the issue we only need a way to customize the display of the top left button, not to know the assembly. As this custom way can be used by several assemblies

**Comment by ashumilova** [comment]
+1

**Comment by benoitf** [comment]
+1

**Pull request merged**
