### PR TITLE
Codenvy-1940: some containers became inaccessible after rebooting

### PR DESCRIPTION
**Pull request by riuvshin**
### What does this PR do?
in order to fix: https://github.com/codenvy/codenvy/issues/1940 afret some investigation i've figured out that our issues were due to using docker logging with syslog which we running as a container. That was a mistake, we should not do that because it works only with compose where we define start order, but when instance or docker daemon reboot containers start in random order which makes failure when image which wants to send logs to syslog started before syslog. And this kind of failures is kind of fatal for docker and docker daemon even don't trying to restart failed container although we've specified `restart: always`.

So here i;ve removed using docker logging with syslog which should fix the issue, but we still need to get logs from containers so i did some changes to make this works same as before.
we had 3 affected images: zookeeper, registry, swarm
For zookeeper i figured how to configure it to write log in to file.
For registry it was enough just to add custom entrypoint where I did log forwarding to file
Unfortunately swarm packaged as just a binary in `scratch` image so there is no bash and no any way to get log, so I added codenvy/swarm image where i get swarm and put in in alpine image which allows me to finally get logs in to a file.

### What issues does this PR fix or reference?
https://github.com/codenvy/codenvy/issues/1940

#### Changelog
fix bug where some containers became inaccessible after rebooting

### CODE REVIEW

**Comment by garagatyi** [comment]
AFAIR we have dependencies between codenvy containers. Am I right? If so then does docker daemon respect it after restart?

**Comment by riuvshin** [comment]
@garagatyi unfortunately - no, as docker guys told me "all depends and ordering things implemented in compose, not docker."

**Comment by garagatyi** [comment]
Then I believe we should not support reloading codenvy on daemon reloading. With your fix it won't be broken because of logging, but because of other things. And it will be broken only sometimes which may make support team life much harder.

**Comment by riuvshin** [comment]
@garagatyi other things covered with entrypoints, for now the only issue with reboot is this one.
and just imagine your prod server was rebooted during the night and system was not self recovered :)

**Comment by garagatyi** [comment]
What do you think about replacing rsyslog container with another container that reads logs of containers using `docker logs -f <container>` and puts logs into our volume mounted directory?

**Comment by riuvshin** [comment]
we've added rsyslog just to get haproxy logs, if i will find a way how to get haproxy logs without rsyslog i will remove rsyslog container. (i'm investigating this now)

**Comment by benoitf** [comment]
BTW it would be nice to get rid of rsyslog container

**Comment by riuvshin** [comment]
@benoitf yeah.. but from what i found haproxy log only to syslog :(
maybe we will replace someday haproxy with nginx but this could be hard...

**Pull request merged**
